origin_url: "https://rapla.dhbw-karlsruhe.de/rapla?page=ical&user=freudenmann&file=TINF23B1"
blocklist:

  # Semester 6
  - Beginn Theorie 6. Semester
  - Start 6. Semester
  - Semesterstart 6.Semester
  - Ende 6. Semester
  - Faschingsdienstag
  - Karfreitag
  - Ostermontag
  - Tag der Arbeit
  - Christi Himmelfahrt
  - Pfingstmontag
  - Fronleichnam
  - Tag der deutschen Einheit
  - Klausuren 6. Semester
  - Klausurwoche 6. Semester
  - High Performance Computing
  - Studienarbeitstag
  - Controlling im Gesundhtswsn (MD)
  - Krankenhausinformationssysteme (MD)
  - Robotik 1
  - Robotik 2
  - Forensik
  - Grundlagen der Finiten Elemente
  - Digitale Audiosignalverarbeitung
  - Explainable AI
  - angewandtes Projektmanagement (eB&PJM)
  - e Business (eB&PJM)
  
  - Klausur Robotik 1+2  (120 min)
  - Klausur High Performance Comp  (90 min)
  - Klausur Erkl채rebare KI  (60 min)
  - Klausur Digitale Augiosignalverarbeitung  (60 min)
  - Klausur Einf체hrung in RUST (60 min)
  - Klausur Finite Elemente  (60 min)
  - Klausur Grundlagen KI und Bildverarbeitung  (120 min)
  - Klausur Grundlagen KI und  Interaktive Systeme  (120 min)
  
  - Management von IT-Infrastrukturen
  - Psychologische Grundlagen f체r Informatiker (W)
  - Einf체hrung in RUST
  - Kolloquium TINF23 Nachtermin  ( min)
  - Grundlagen KI (aus KI und IS)
  - Grundlagen KI (aus KI und BV)

  - Abschlussexkursion Prag
  - Exkursion DEMEA (Medizinische Informatik)
